# This the path that will lead to the folder
# that contains the separated config
$configsPath = ~/.config/hypr/configs

################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preffered,auto,1

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
$primaryMonitor = monitor:HDMI-A-1
$secondaryMonitor = monitor:eDP-1

workspace = 1, $primaryMonitor
workspace = 2, $secondaryMonitor
workspace = 3, $primaryMonitor
workspace = 4, $secondaryMonitor
workspace = 5, $primaryMonitor

###################
###   STARTUP   ###
###################

source = $configsPath/hyprland-startup.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = $configsPath/hyprland-env.conf

#####################
### LOOK AND FEEL ###
#####################

source = $configsPath/hyprland-look.conf

#############
### INPUT ###
#############

source = $configsPath/hyprland-input.conf

####################
### KEYBINDINGSS ###
####################

source = $configsPath/hyprland-keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = $configsPath/hyprland-rules.conf

