#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = XCURSOR_THEME, NightDiamond
# See this documentation to import the cursor themes to the hyprcursor to work in both X11 and Wayland applications
# https://github.com/hyprwm/hyprcursor/blob/main/docs/MAKING_THEMES.md
env = HYPRCURSOR_THEME, NightDiamond
env = HYPRCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,auto

env = QT_STYLE_OVERRIDE,kvantum
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QUICK_CONTROLS_STYLE,org.hyprland.style

#####################################
#   Nvidia Environment-variables    #
#####################################

# Hardware acceleration on NVIDIA GPUs
# (https://wiki.archlinux.org/title/Hardware_video_acceleration)
env = LIBVA_DRIVER_NAME,nvidia

# (https://wiki.archlinux.org/title/Wayland#Requirements)
# WARN: crashes me hyprland
# env = GBM_BACKEND,nvidia-drm
# To force GBM as a backend
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# set to 1 to use software cursors instead of hardware cursors
# (https://wiki.hyprland.org/hyprland-wiki/pages/Nvidia/)
env = WLR_NO_HARDWARE_CURSORS,1

# TIP: Advantage is all the apps will be running on nvidia
# WARN: crashes whatever window's opened after "hibranate"
env = __NV_PRIME_RENDER_OFFLOAD,1

# Controls if G-Sync capable monitors should use Variable Refresh Rate (VRR)
# See Nvidia Documentation for details.
# (https://download.nvidia.com/XFree86/Linux-32bit-ARM/375.26/README/openglenvvariables.html)
env = __GL_GSYNC_ALLOWED,0

# Controls if Adaptive Sync should be used. Recommended to set as “0” to avoid
# having problems on some games.
env = __GL_VRR_ALLOWED,0

env = __VK_LAYER_NV_optimus,NVIDIA_only
env = NVD_BACKEND,direct

