###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = nemo
$menu = rofi -show drun
$browser = librewolf
$discord = vesktop
$email = thunderbird
$spotify = spotify-launcher

#################
### AUTOSTART ###
#################

# Autostart necessary processes and applications


# Set wallpaper and cursor theme
exec-once = hyprpaper

# Start status bar
exec-once = waybar

# Disabled for now as I don't use it
# Might change to turn off monitor for when I use hyprlock
# exec-once = hypridle

# Network management and notifications
# Using iwd and impala for wifi
# systemd-resolve for the DNS solving
# DHCP (currently I don't know who is doing it maybe NetworkManager but can switch for networkd?)
# exec-once = nm-applet &
exec-once = dunst -conf .config/dunst/dunstrc

# Environment setup for Wayland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
# exec-once = dbus-update-activation-environment --systemd --all
# Replaced now for the hyprland polkit agent
# exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent
# exec-once = systemctl --user enable --now hyprpolkitagent.service

# Start browser, discord, email client and spotify
exec-once = $browser
exec-once = $discord

# Start email client and system tray app
exec-once = $email

exec-once = $spotify
